re-arrange fields to match key
jalapeno/lslinknode-edge pull request #4
Opened 2021-02-13 19:00 UTC by brmcdoug

2021-02-13 19:37 UTC, sbezverk requested changes

2021-02-13 19:37 UTC, sbezverk commented on pkg/arangodb/edge.go
> +	FromLSNode string       `json:"from_lsnode"`
Line 97 and Link 98 look duplication to me, what is the value to have the same info?

2021-02-13 19:37 UTC, sbezverk commented on pkg/arangodb/edge.go
> +		FromLSNode: ln.Name,
Same comment as above

2021-02-13 23:29 UTC, brmcdoug commented on pkg/arangodb/edge.go
> +	FromLSNode string       `json:"from_lsnode"`
good point.  i was experimenting with adding node name, but this info can easily be found in LSNode collection

2021-02-13 23:30 UTC, brmcdoug commented on pkg/arangodb/edge.go
> +		FromLSNode: ln.Name,
same reply.  removed in latest commit

2021-02-14 14:01 UTC, sbezverk approved these changes

2021-02-14 14:02 UTC, merged